const buzzwords = [
  "Animes", "Gymgir", "Altgirls", "Baddies", "Brooke", "Pineville",
  "Eclipse", "Memes", "Armybts", "Loves", "Brickedup", "Aifilter",
  "Erastour", "Badbunny", "Solareclipse", "Badbunnypr", "Bestvideo", "Gaza",
  "Erastourmovie", "Steam", "Tommyfury", "Boxing", "Misfitsboxing", "Loganpaul",
  "Fight", "Halloweenspirit", "Halloweenlover", "Halloweenobsessed", "Love",
  "Instagood", "Fashion", "Photooftheday", "Photography", "Art", "Halloweenmonth",
  "Halloweenfun", "Halloweenseason", "Beautiful", "Nature", "Picoftheday",
  "Happy", "Halloween", "Autumnvibes", "Halloweenvibes", "Halloweenaesthetic",
  "Trending", "Explorepage", "Viral", "Tbt", "Like4like",
  "Followme", "Youtubechannel", "Youtube", "Youtuber", "Youtubers",
  "Subscribe", "Youtubevideos", "Sub", "Youtubevideo", "Like", "Instagram",
  "Follow", "Video", "Vlog", "Subscribetomychannel", "Gaming", "Music",
  "Smallyoutuber", "Vlogger", "Youtubegaming", "Gamer", "Youtubecommunity",
  "Likes", "Explore", "Youtubelife", "Youtubecreator", "Ps", "Bhfyp",
  "DigitalMarketing", "TechNews", "SelfCareSunday", "Innovation", "FitnessGoals",
  "FoodieFriday", "MondayMotivation", "ThrowbackThursday", "FashionTrends",
  "EntrepreneurLife", "TravelTuesday", "GamingCommunity", "Podcast", "ArtisticExpression",
  "BookLovers", "PositiveVibes", "PetLovers", "Wellness", "HealthyLiving",
  "StartupLife", "India", "Management", "HumanResources", "Technology",
  "Creativity", "Future", "Futurism", "Entrepreneurship", "Careers",
  "Markets", "Startups", "Marketing", "SocialMedia", "VentureCapital", "SocialNetworking",
  "LeanStartups", "Economy", "Economics", "Branding", "Personaldevelopment",
  "Sustainability", "Travel", "love", "instagood", "fashion", "photooftheday",
  "beautiful", "artist", "design", "photography", "happy", "picoftheday",
  "follow", "tbt", "followme", "nature", "like4like", "travel",
  "instagram", "style", "repost", "summer", "instadaily", "selfie", "me", "friends",
  "fitness", "girl", "food", "funny", "beauty", "instalike", "smile",
  "family", "photo", "life", "likeforlike", "music", "ootd", "follow4follow", "makeup",
  "amazing", "igers", "nofilter", "dogsofinstagram", "model", "sunset",
  "beach", "instamood", "foodporn", "motivation", "trending", "likes", "like",
  "likeforlikes", "followforfollowback", "fyp", "l", "myself", "likeforfollow",
  "followers", "followback", "f", "followforfollow", "comment", "likesforlikes", "bhfyp",
  "reels", "reelsvideo", "reelsinstagram", "reelsindia", "holareels", "reelsbrasil",
  "reelsteady", "instagramreels", "reelsinsta", "instareels", "reelsofinstagram", "k",
  "disney", "littlestoriesofmylife", "tiktokindia", "videoftheday", "instareel",
  "foryoupage", "reelsviral", "haul", "shopping", "styleinspo", "outfitoftheday",
  "outfit", "whatiwore", "shoppingaddict", "beautydoesnthavetobepain", "currentlywearing",
  "instastyle", "lookgoodfeelgood", "hippy", "fashionblogger", "fashionista", "fashionstyle",
  "fashionable", "fashiongram", "fashionblog", "fashionaddict", "fashionphotography", "foodie",
  "instafood", "foodphotography", "foodstagram", "yummy", "yum", "foodblogger",
  "foodlover", "delicious", "homemade", "healthyfood", "dinner", "foodgasm", "foodies",
  "tasty", "cooking", "lunch", "takeout", "restaurant", "healthy", "travelphotography",
  "travelgram", "art", "naturephotography", "wanderlust", "adventure", "instatrave",
  "travelblogger", "landscape", "trip", "hike", "explore", "pet",
  "dog", "pets", "cute", "petsofinstagram", "dogs", "cat", "puppy", "cats", "petstagram",
  "animals", "animal", "instadog", "dogstagram", "doglover", "of",
  "catsofinstagram", "dogoftheday", "doglovers", "petlovers", "doglife", "instapet",
  "catstagram", "cachorro", "catlover", "techie", "latesttech", "ilovemygadgets",
  "gadgetsgalore", "apple", "android", "applevsandroid", "wearabletech", "VR",
  "mobile", "makinglifeeasier", "tech", "technology", "technews", "gadgets", "instatech",
  "software", "innovation", "wedding", "bride", "weddingdress", "weddingphotography", "weddingday",
  "weddinginspiration", "weddingplanner", "prewedding", "bridal", "bridetobe",
  "weddingphotographer", "weddings", "groom", "engagement", "party",
  "weddingideas", "makeupartist", "indianwedding", "casamento", "gym", "workout",
  "fitnessmotivation", "fit", "bodybuilding", "training", "health", "lifestyle", "fitfam",
  "healthylifestyle", "sport", "gymlife", "crossfit", "personaltrainer", "goals",
  "exercise", "muscle", "stockingstuffers", "christmasdecor", "spookyhalloween", "happyhalloween",
  "thanksgivingtable", "turkeyorham", "valentineformyvalentine", "happyfourth", "newyearseve",
  "newyearsresolution", "holidaycrazy", "holidayspirit", "kwanza", "hanukkahgift",
  "underthetree", "instacontest", "instagiveaway", "giveaway", "sweepstakes", "contestalert",
  "contestentry", "winit", "freebie", "winitwednesday", "photographer", "photoshoot",
  "portrait", "canon", "fotografia", "portraitphotography", "photographylovers", "nikon",
  "business", "businesstips", "marketing", "ecommerce", "socialmedia", "digitalmarketing (28M)",
  "SEO", "contentmarketing", "marketingstrategy", "consulting", "workplace", "startups",
  "productivity", "strategy", "sales", "smallbusiness", "supportsmallbusiness", "handmade",
  "shoplocal", "shopsmall", "smallbusinessowner", "entrepreneur", "supportlocal", "localbusiness",
  "businessowner", "blackownedbusiness", "explorepage", "homedecor", "covid",
  "startup", "entrepreneurship", "womeninbusiness", "success", "girlboss", "entrepreneurlife",
  "handcrafted", "local", "smallbiz", "custom", "smallbusinesssupport", "shopsmallbusiness",
  "handmadewithlove", "supportsmallbusinesses", "supportlocalbusiness", "hiphop", "rap",
  "musician", "singer", "musica", "dj", "rock", "dance", "song", "guitar", "viral", "producer",
  "newmusic", "musicvideo", "instamusic", "livemusic", "pop", "concert", "trap",
  "beats", "drawing", "artwork", "painting", "artistsoninstagram", "illustration", "digitalart", "sketch", "flowers",
  "wildlife", "mountains", "hiking", "outdoors", "naturelover", "forest"
];

const hashtags = buzzwords.map(bw => ({ id: bw, display: bw }));

export default hashtags;